version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing root dependencies...
      - npm install
      - echo Installing server dependencies...
      - cd server
      - npm install
      - echo Installing client dependencies...
      - cd ../client
      - npm install

  pre_build:
    commands:
      - echo "Checking used ports..."
      - lsof -i -P -n

  build:
    commands:
      - echo Building the server...
      - cd ../server
      - npm run build
      - echo Building the client...
      - cd ../client
      - npm run build

  post_build:
    commands:
      - echo Starting server and client concurrently...
      - cd ../
      - concurrently "npm run server" "npm run client"

artifacts:
  files:
    - '**/*'  # Include all files for deployment
  base-directory: client/build  # Adjust this if your build output is in a different location