  version: 0.2

  phases:
    install:
      runtime-versions:
        nodejs: 20
      commands:
        - echo Installing dependencies...
        - npm install
        - cd server
        - npm install
        - cd ../client
        - npm install

  build:
    commands:
      - echo Building the client...
      - cd ../client
      - npm run build
      - ls -la

  post_build:
    commands:
      - echo Starting the server...
      - cd ../
      - npm start  # Start the Node.js server

   artifacts:
     files:
       - '**/*'
     base-directory: client/build